version: '3'

services:
  boilerplate-api:
    container_name: 'boilerplate-api'
    depends_on:
      - boilerplate-database
    restart: always
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  boilerplate-database:
    container_name: 'boilerplate-database'
    image: postgres:alpine
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  boilerplate-admin:
    container_name: 'boilerplate-admin'
    image: adminer
    restart: always
    ports:
      - ${DATABASE_ADMIN_PORT}:${DATABASE_ADMIN_PORT}

volumes:
  pg-data:
